name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npx cap add ios --confirm
        npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install iOS dependencies
      run: |
        cd ios/App
        pod install
        
    - name: Build iOS app (Debug)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath App.xcarchive \
          archive
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios/App/App.xcarchive
        retention-days: 30

  # Optional: Build for App Store (requires certificates)
  build-ios-release:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-ios
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npx cap add ios --confirm
        npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install iOS dependencies
      run: |
        cd ios/App
        pod install
        
    # Note: For App Store builds, you'll need to add:
    # - Apple Developer certificates as GitHub secrets
    # - Provisioning profiles
    # - Code signing configuration
    
    - name: Build for App Store (placeholder)
      run: |
        echo "App Store build requires Apple Developer certificates"
        echo "Add your certificates to GitHub Secrets to enable this step"
        echo "See: https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development"
