name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npm install -g @capacitor/cli@latest
        npm install @capacitor/core@latest @capacitor/ios@latest
        
    - name: Initialize Capacitor (if needed)
      run: |
        if [ ! -f "capacitor.config.ts" ]; then
          npx cap init "REDash" "com.redash.app" --web-dir=dist
        fi
        
    - name: Add iOS platform
      run: npx cap add ios
      
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
        
    - name: Update CocoaPods and clear cache
      run: |
        sudo gem install cocoapods --force
        pod repo update
        pod cache clean --all
        
    - name: Create minimal Podfile
      run: |
        cat > ios/App/Podfile << 'EOF'
        require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

        platform :ios, '13.0'
        use_frameworks!

        def capacitor_pods
          pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
          pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
        end

        target 'App' do
          capacitor_pods
        end

        post_install do |installer|
          assertDeploymentTarget(installer)
        end
        EOF
        
    - name: Install iOS dependencies with verbose output
      run: |
        cd ios/App
        pod install --verbose --repo-update
        
    - name: Sync Capacitor
      run: npx cap sync ios
        
    - name: List ALL available simulators and runtimes
      run: |
        echo "=== Available Runtimes ==="
        xcrun simctl list runtimes
        echo ""
        echo "=== Available Device Types ==="
        xcrun simctl list devicetypes
        echo ""
        echo "=== Available Devices ==="
        xcrun simctl list devices available
        echo ""
        echo "=== Xcode Version ==="
        xcodebuild -version
        
    - name: Find and use any available iOS simulator
      id: find-simulator
      run: |
        # Get any available iOS device (just pick the first one)
        DEVICE_LINE=$(xcrun simctl list devices available | grep "iPhone" | head -1)
        echo "Found device line: $DEVICE_LINE"
        
        # Extract device name (everything before the first parenthesis)
        DEVICE_NAME=$(echo "$DEVICE_LINE" | sed 's/^[[:space:]]*//' | sed 's/ (.*//')
        echo "Extracted device name: $DEVICE_NAME"
        
        # Get the iOS version from the section header
        IOS_VERSION=$(xcrun simctl list devices available | grep -B 10 "$DEVICE_LINE" | grep "-- iOS" | tail -1 | sed 's/.*iOS \([0-9.]*\).*/\1/')
        echo "Extracted iOS version: $IOS_VERSION"
        
        # Set outputs
        echo "device_name=$DEVICE_NAME" >> $GITHUB_OUTPUT
        echo "ios_version=$IOS_VERSION" >> $GITHUB_OUTPUT
        
        echo "Will use: platform=iOS Simulator,name=$DEVICE_NAME,OS=$IOS_VERSION"
        
    - name: Build iOS app for simulator
      run: |
        cd ios/App
        echo "Building with destination: platform=iOS Simulator,name=${{ steps.find-simulator.outputs.device_name }},OS=${{ steps.find-simulator.outputs.ios_version }}"
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -destination "platform=iOS Simulator,name=${{ steps.find-simulator.outputs.device_name }},OS=${{ steps.find-simulator.outputs.ios_version }}" \
          -derivedDataPath ./build \
          build
          
    - name: Build iOS app for device (unsigned)
      run: |
        cd ios/App
        # Build for device without code signing (for CI)
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination "generic/platform=iOS" \
          -derivedDataPath ./build-device \
          build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      continue-on-error: true
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ios/App/build
          ios/App/build-device
        retention-days: 30
        if-no-files-found: warn
