name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Setup Capacitor
      run: |
        npm install -g @capacitor/cli@latest
        npm install @capacitor/core@latest @capacitor/ios@latest
        
    - name: Initialize Capacitor (if needed)
      run: |
        if [ ! -f "capacitor.config.ts" ]; then
          npx cap init "REDash" "com.redash.app" --web-dir=dist
        fi
        
    - name: Add iOS platform
      run: npx cap add ios
      
    - name: Check available Xcode versions
      run: |
        echo "=== Available Xcode Versions ==="
        ls /Applications/ | grep -i xcode
        echo ""
        echo "=== Current Xcode Version ==="
        xcodebuild -version
        echo ""
        echo "=== Available iOS Simulators ==="
        xcrun simctl list devices available
        echo ""
        echo "=== Available Runtimes ==="
        xcrun simctl list runtimes
        
    - name: Update CocoaPods and clear cache
      run: |
        sudo gem install cocoapods --force
        pod repo update
        pod cache clean --all
        
    - name: Create minimal Podfile
      run: |
        cat > ios/App/Podfile << 'EOF'
        require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

        platform :ios, '13.0'
        use_frameworks!

        def capacitor_pods
          pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
          pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
        end

        target 'App' do
          capacitor_pods
        end

        post_install do |installer|
          assertDeploymentTarget(installer)
        end
        EOF
        
    - name: Install iOS dependencies
      run: |
        cd ios/App
        pod install --repo-update
        
    - name: Sync Capacitor
      run: npx cap sync ios
        
    - name: Find available iOS simulator
      id: find-simulator
      run: |
        echo "=== Finding Available iOS Simulator ==="
        
        # Get the first available iPhone simulator (any version)
        SIMULATOR_INFO=$(xcrun simctl list devices available | grep "iPhone" | head -1)
        echo "Found simulator line: $SIMULATOR_INFO"
        
        if [ -z "$SIMULATOR_INFO" ]; then
          echo "No iPhone simulators found, trying iPad..."
          SIMULATOR_INFO=$(xcrun simctl list devices available | grep "iPad" | head -1)
        fi
        
        if [ -z "$SIMULATOR_INFO" ]; then
          echo "No simulators found at all!"
          exit 1
        fi
        
        # Extract device name (everything before the first parenthesis)
        DEVICE_NAME=$(echo "$SIMULATOR_INFO" | sed 's/^[[:space:]]*//' | sed 's/ (.*//')
        echo "Device name: $DEVICE_NAME"
        
        # Get iOS version from the section header above this device
        IOS_VERSION=$(xcrun simctl list devices available | grep -B 20 "$SIMULATOR_INFO" | grep "-- iOS" | tail -1 | sed 's/.*iOS \([0-9.]*\).*/\1/')
        echo "iOS version: $IOS_VERSION"
        
        # Fallback: if we can't extract version, use any available runtime
        if [ -z "$IOS_VERSION" ]; then
          IOS_VERSION=$(xcrun simctl list runtimes | grep "iOS" | head -1 | sed 's/.*iOS \([0-9.]*\).*/\1/')
          echo "Fallback iOS version: $IOS_VERSION"
        fi
        
        echo "device_name=$DEVICE_NAME" >> $GITHUB_OUTPUT
        echo "ios_version=$IOS_VERSION" >> $GITHUB_OUTPUT
        
        echo "Will use destination: platform=iOS Simulator,name=$DEVICE_NAME,OS=$IOS_VERSION"
        
    - name: Build iOS app for simulator
      run: |
        cd ios/App
        echo "Building for simulator with destination: platform=iOS Simulator,name=${{ steps.find-simulator.outputs.device_name }},OS=${{ steps.find-simulator.outputs.ios_version }}"
        
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -destination "platform=iOS Simulator,name=${{ steps.find-simulator.outputs.device_name }},OS=${{ steps.find-simulator.outputs.ios_version }}" \
          -derivedDataPath ./build \
          build
          
    - name: Build iOS app for device (generic)
      run: |
        cd ios/App
        echo "Building for generic iOS device..."
        
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination "generic/platform=iOS" \
          -derivedDataPath ./build-device \
          build \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      continue-on-error: true
        
    - name: Archive iOS app
      run: |
        cd ios/App
        echo "Creating archive..."
        
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Release \
          -destination "generic/platform=iOS" \
          -archivePath ./REDash.xcarchive \
          archive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
      continue-on-error: true
        
    - name: Create IPA (if archive succeeds)
      run: |
        cd ios/App
        if [ -d "./REDash.xcarchive" ]; then
          echo "Creating IPA from archive..."
          xcodebuild -exportArchive \
            -archivePath ./REDash.xcarchive \
            -exportPath ./export \
            -exportOptionsPlist ../../export-options.plist
        else
          echo "Archive not found, skipping IPA creation"
        fi
      continue-on-error: true
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: |
          ios/App/build
          ios/App/build-device
          ios/App/export
          ios/App/REDash.xcarchive
        retention-days: 30
        if-no-files-found: warn
