name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build React app
      run: npm run build
      
    - name: Install Capacitor packages
      run: |
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/ios
      
    - name: Add iOS platform
      run: npx cap add ios
      
    - name: Update iOS deployment target
      run: |
        # Update the iOS deployment target to iOS 13.0 (required for Capacitor 6+)
        sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g' ios/App/App.xcodeproj/project.pbxproj
        
        # Also update the Podfile to specify iOS 13.0
        echo "platform :ios, '13.0'" > ios/App/Podfile.tmp
        tail -n +2 ios/App/Podfile >> ios/App/Podfile.tmp
        mv ios/App/Podfile.tmp ios/App/Podfile
        
    - name: Sync Capacitor
      run: npx cap sync ios
        
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Install iOS dependencies
      run: |
        cd ios/App
        pod repo update
        pod install --repo-update
        
    - name: Build iOS app (Debug)
      run: |
        cd ios/App
        xcodebuild -workspace App.xcworkspace \
          -scheme App \
          -configuration Debug \
          -destination 'generic/platform=iOS Simulator' \
          -archivePath App.xcarchive \
          archive
          
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios/App/App.xcarchive
        retention-days: 30
