The job failed because the requested iOS Simulator device ({ platform:iOS Simulator, OS:16.4, name:iPhone 14 }) could not be found. The error log says:

Unable to find a device matching the provided destination specifier: { platform:iOS Simulator, OS:16.4, name:iPhone 14 }
The requested device could not be found because no available devices matched the request.

Solution
You need to make sure the runner has the required iOS Simulator installed. Here’s how you can fix this:

Update the Workflow Device Specifier

Change the simulator OS version to one available on GitHub-hosted runners. iOS 16.4 may not be installed; try a more common version like 17.2 or the latest supported by your runner.

Example change in your workflow (see .github/workflows/ios-build.yml):

YAML
- name: Build iOS App
  run: |
    xcodebuild \
      -workspace App.xcworkspace \
      -scheme App \
      -destination 'platform=iOS Simulator,OS=17.2,name=iPhone 14' \
      build
List Available Simulators Before Build

Add a step to show available simulators, which helps to select a valid destination:

YAML
- name: List available simulators
  run: xcrun simctl list devices
Install Required Simulator Version (if using a self-hosted runner)

If you're using a self-hosted runner, install the missing simulator via Xcode’s Preferences or command line.
